(()=>{const $=id=>document.getElementById(id),rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,pick=a=>a[rnd(0,a.length-1)];
const surnames=["Tang","Ning","Dai","Zhu","Yu","Ma","Chen","Lin","Ye","Bai","Su","Mu"],male=["Hao","Wei","Feng","Lei","Jun","Ming","Chen","Long","Shan","Tian"],female=["Yue","Xue","Ling","Mei","Rong","Lan","Hua","Yan","Qing","Yun"],qualityNames=["Common","Good","High","Superior","Top"];
const all=[...SOUL_DB.tool.map(name=>({name,type:"Tool"})),...SOUL_DB.beast.map(name=>({name,type:"Beast"})),...SOUL_DB.body.map(name=>({name,type:"Body"}))];let s;
function spirit(){const x={...pick(all)};x.quality=rnd(1,5);return x}
function log(t){s.log.unshift(t);s.log=s.log.slice(0,10)}
function reset(){let f=spirit(),m=spirit();while(m.name===f.name)m=spirit();const family=pick(surnames);s={age:6,playerName:family+" "+pick(male),fatherName:family+" "+pick(male),motherName:pick(surnames)+" "+pick(female),father:f,mother:m,awakened:false,primary:null,second:null,innate:0,rank:0,rankXP:0,soulPower:0,spiritual:rnd(8,18),comprehension:0,rings:[],log:[]};log("Keluarga baharu dijana. Martial Soul belum dibangkitkan.");render()}
function stronger(){if(s.father.quality>s.mother.quality)return s.father;if(s.mother.quality>s.father.quality)return s.mother;return Math.random()<.5?s.father:s.mother}
function twinChance(){if(s.father.name===s.mother.name)return 0;const d=Math.abs(s.father.quality-s.mother.quality);return d===0?.003:d===1?.001:0}
function mutationChance(){if(s.father.name===s.mother.name)return .02;return Math.abs(s.father.quality-s.mother.quality)<=1?.08:.035}
function awaken(){if(s.awakened)return;const r=Math.random(),tc=twinChance(),mc=mutationChance();if(r<tc){s.primary={...s.father};s.second={...s.mother};s.innate=10;log("Rare awakening: Twin Martial Souls.")}else if(r<tc+mc){const b=stronger();s.primary={name:"Mutated "+b.name,type:b.type,quality:Math.min(5,b.quality+1)};s.innate=rnd(4,10);log("Spirit Mutation berlaku semasa awakening.")}else{s.primary={...stronger()};s.innate=rnd(0,10);log("Martial Soul diwarisi daripada garis keturunan keluarga.")}s.awakened=true;s.soulPower=s.innate;s.rank=s.innate>0?s.innate:0;log("Innate Soul Power: "+s.innate+".");render()}
function ring(){const i=s.rings.length,b=[100,300,700,1200,2500,5000,10000,30000,60000][Math.min(i,8)],age=b+rnd(0,Math.floor(b*.4)),skills=age>=100000?2:1;s.rings.push({age,skills});log("Soul Ring "+age+" tahun diperoleh ("+skills+" Soul Skill).")}
function cultivate(){if(!s.awakened||s.innate===0)return;s.rankXP+=rnd(12,26)+Math.floor(s.comprehension/15);s.soulPower=Math.min(100,s.soulPower+rnd(1,3));s.spiritual=Math.min(100,s.spiritual+rnd(0,2));while(s.rankXP>=100&&s.rank<99){s.rankXP-=100;s.rank++;log("Breakthrough: Rank "+s.rank+".");if(s.rank%10===0&&s.rings.length<Math.floor(s.rank/10))ring()}render()}
function comprehend(){if(!s.awakened)return;const g=rnd(3,7);s.comprehension=Math.min(100,s.comprehension+g);s.spiritual=Math.min(100,s.spiritual+rnd(1,3));log("Comprehension meningkat +"+g+".");render()}
function stage(){const c=s.comprehension;if(c>=90)return"Advanced Law Comprehension";if(c>=75)return"One with the Heavens";if(c>=50&&s.primary&&/Element/i.test(s.primary.name))return"Element's Heart";if(c>=35)return"Martial Soul Approval / True Essence";if(c>=18)return(s.primary?.name||"Weapon")+" Consciousness";return"Basic Understanding"}
function milestones(){const elem=s.primary&&/Element|Fire|Ice|Water|Wind|Lightning|Thunder|Earth|Light|Dark/i.test(s.primary.name),list=[["Basic Understanding",10,true],["Martial Soul Approval / True Essence",35,true],["Element's Heart",50,elem],["One with the Heavens",75,true],["Laws of Heaven and Earth",90,s.rank>=90]];$("milestones").innerHTML="";list.forEach(([n,need,ok])=>{const u=ok&&s.comprehension>=need,d=document.createElement("div");d.className="milestone"+(u?" unlocked":"");d.innerHTML="<strong>"+n+"</strong><small>"+(ok?(u?"Unlocked":"Requires "+need+"%"):"Not currently eligible")+"</small>";$("milestones").appendChild(d)})}
function render(){$("age").textContent=s.age;$("playerName").textContent=s.playerName;$("rank").textContent=s.rank;$("soulPower").textContent=s.soulPower;$("spiritual").textContent=s.spiritual;$("comprehension").textContent=s.comprehension;$("rankLabel").textContent=s.awakened?(s.innate===0?"No innate Soul Power":"Soul Master Rank "+s.rank):"Belum menjadi Soul Master";$("fatherName").textContent=s.fatherName;$("motherName").textContent=s.motherName;$("fatherSoul").textContent=s.father.name;$("motherSoul").textContent=s.mother.name;$("fatherType").textContent=s.father.type+" Spirit";$("motherType").textContent=s.mother.type+" Spirit";$("fatherQuality").textContent="Quality: "+qualityNames[s.father.quality-1];$("motherQuality").textContent="Quality: "+qualityNames[s.mother.quality-1];$("cultivateBtn").disabled=!s.awakened||s.innate===0;$("comprehendBtn").disabled=!s.awakened;$("rankBar").style.width=s.rankXP+"%";$("rankProgress").textContent=s.rankXP+" / 100";$("compBar").style.width=s.comprehension+"%";$("compStage").textContent=stage();if(s.awakened){$("awakeningResult").classList.remove("muted");$("awakeningResult").innerHTML="<strong>"+s.primary.name+"</strong><br>"+s.primary.type+" Spirit · Innate Soul Power "+s.innate;$("orbText").textContent=s.primary.name.slice(0,2).toUpperCase();$("awakenBtn").disabled=true;$("awakenBtn").textContent="Awakened";if(s.second){$("secondSoulPanel").classList.remove("hidden");$("secondSoul").textContent=s.second.name}else $("secondSoulPanel").classList.add("hidden")}else{$("awakeningResult").textContent="Martial Soul belum dibangkitkan. Pemain tidak boleh memilih Martial Soul.";$("awakeningResult").classList.add("muted");$("orbText").textContent="?";$("awakenBtn").disabled=false;$("awakenBtn").textContent="Awaken";$("secondSoulPanel").classList.add("hidden")}$("rings").innerHTML="";if(!s.rings.length)$("rings").innerHTML='<p class="muted">Belum ada Soul Ring.</p>';else s.rings.forEach((r,i)=>{const d=document.createElement("div");d.className="ring";d.innerHTML="<strong>Ring "+(i+1)+"</strong><br><small>"+r.age+" years · "+r.skills+" skill"+(r.skills>1?"s":"")+"</small>";$("rings").appendChild(d)});milestones();$("log").innerHTML="";s.log.forEach(t=>{const p=document.createElement("p");p.textContent=t;$("log").appendChild(p)})}
$("newGameBtn").onclick=reset;$("awakenBtn").onclick=awaken;$("cultivateBtn").onclick=cultivate;$("comprehendBtn").onclick=comprehend;reset()})();